apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance.name }}
spec:
  selector:
    app: {{ .Values.instance.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 18789
  type: {{ .Values.service.type }}
